### ISSUE TITLE
[BUG] TintEffect PrepareFrame and ProcessFrame constantly triggered and overwriting the color

### ISSUE THREAD

**Issue by Maesla** [MixedRealityToolkit/MixedRealityToolkit-Unity#661] opened 2024-02-27 13:34 UTC
## Describe the bug

TintEffect PrepareFrame and ProcessFrame are called constantly, although statevisualizer is disabled and even the effect is not applied

They both call ApplyColor, so they prevent to apply any color from an outside script if the state visualizer contains any state with a TintEffect.

Even if you remove those effects in runtime from the list, it's not enough, the methods keep being called

## To reproduce

1. Create a clean scene with a button
2. Remove all the effects but one in the statevisualizer. The remaining one should be a TintEffect, like GraphicTintEffect
3. Play the scene
4. Add a break point to TintEffect.ProcessFrame and TintEffect.PrepareFrame and see how they are called constantly
5. Create a script that changes the color of the GraphicTintEffect. See that the color can not be changed because GraphicTintEffect reapplies the color all the time

## Expected behavior

Those methods should be called when necessary

## Screenshots
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/25863696/296b0fda-678a-4e60-b551-28c589b827ab)

In the video, you can see that only removing statevisualizer allows to change the button color. The effect list is empty. The effects on ToggleState are overwritting the color

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/25863696/5f318400-81da-4a48-bd4a-912d490c709f

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.21f1]
- MRTK Version or Commit 0bf1b5c5e0e74c30e37930b6c430e2258b9e8ff5
## Target platform (please complete the following information)
- UnityEditor

## Additional context

Script to try to change the color. Only removing completely statevisualiser allows to change the color. Removing the effects for the lists is not enough
```csharp
using MixedReality.Toolkit;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.XR.Interaction.Toolkit;

public class StateVisualizerDebug : MonoBehaviour
{
    public StatefulInteractable interactable;

    public Color c;
    public RawImage image;

    private void Start()
    {
        interactable.selectEntered.AddListener(OnSelectEntered);
    }

    private void OnSelectEntered(SelectEnterEventArgs arg0)
    {
        Debug.Log("OnSelectEntered");
    }

    private void Update()
    {
        if(Input.GetKeyDown(KeyCode.Z))
        {
            ChangeColor();
        }
    }

    private void OnGUI()
    {
        if (GUI.Button(new Rect(0, 0, 200, 200), "Change Color"))
        {
            ChangeColor();
        }
    }

    private void ChangeColor()
    {
        image.color = c;
    }
}

```

PS: As minor error, The ToggleState is taken into account even when the PressableButton is not a toggle. It gets hidden, but if you have added an effect in the ToggleState and then you transform the PressableButtom from Toggle to Button, the state gets hidden but the effects remain

**Comment by Maesla** [comment] 2024-02-27 15:14
isHovered was returning true all the time so the graph wasn't stopped. 
```csharp
                if (sleepTimer <= 0 && interactable != null && !interactable.isSelected && !interactable.isHovered)
                {
                    // All effects are done, let's go to sleep.
                    animator.enabled = false;
                    playableGraph.Stop();
                    enabled = false;
                }
```

I am still having problems to change colors but probably because TintEffect is caching the color

You can close the issue, although the ToggleState effecting PressableButtons that are not toggles but hidding the state in the inspector is still an issue

**Comment by Maesla** [comment] 2024-02-27 16:04
Finally I made it work as a prototype adding this method to StateVisualizer and calling from outside when I change colors

```csharp
        public void Stop()
        {
            animator.enabled = false;
            playableGraph.Stop();
            enabled = false;
            sleepTimer = 0;
        }
```

Could it possible to add it officially?

**Comment by AMollis** [comment] 2024-03-11 16:20
@ms-RistoRK can you please investigate this.

**Comment by ms-RistoRK** [comment] 2024-03-11 21:24
@Maesla Thank you for sharing with us the issue you are experiencing.  I also noticed that you already have a working solution to the issue and request it to be added as part of the code-base, that's fantastic, we greatly appreciate pro-activity from any member of this open-source project.
Since this is an open-source project, the decision to make changes on the code-base does not reside on a single person and it is rather a consensual decision between all parties to make any change.  For that purpose and also to properly recognize the effort you have done already in finding the solution I invite you to submit a Pull Request (PR) and a panel of specialists will review it and provide feedback.  Since you mentioned that this issue can be closed I would encourage that you submit your solution as part of a feature request.
I'll be happy to provide guiding information regarding repository philosophy and coding guidelines for your Pull Request, both aspects are greatly appreciated by the expert's panel.  Once again, my sole goal is that you are properly recognized as the code repository contributor that found the solution and helped improve this open-source project, and I'll be happy to help you achieve that.
Having said that, How do you prefer to proceed?  Would you like to open a feature request or would you prefer to submit a PR for this issue?

**Comment by Maesla** [comment] 2024-03-12 10:48
Well, since this is about StateVisualizer , which is probably one of the more ubiquitous component in the whole package and also a quite complex one (using states, playables, playable graphs, etc), I wanted to be very cautious with the solution.

But ok, I'll provide a PR and we can discuss it from there.

About keeping the bug open or not, maybe it is better to associate the bug with the PR and keep it open until the PR is merged

**Comment by ms-RistoRK** [comment] 2024-03-13 00:27
> Well, since this is about StateVisualizer , which is probably one of the more ubiquitous component in the whole package and also a quite complex one (using states, playables, playable graphs, etc), I wanted to be very cautious with the solution.
> 
> But ok, I'll provide a PR and we can discuss it from there.
> 
> About keeping the bug open or not, maybe it is better to associate the bug with the PR and keep it open until the PR is merged

Great!, here is link to the coding guidelines the experts panel suggest to follow: https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/contributing/coding-guidelines?view=mrtkunity-2022-05#access-modifiers

**Comment by ms-RistoRK** [comment] 2024-03-19 15:49
Friendly notification: Another contributor is also asking for a change in StateVisualizer https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/584

**Comment by ms-RistoRK** [comment] 2024-03-19 20:22
Hello @Maesla; I took another look at this issue with Unity 2021.3.21f1 and MRTK3 commit https://github.com/ms-RistoRK/MixedRealityToolkit-Unity/commit/f279218d1e1f0856ebb32c6122b0b22a273a15d6 and I am unable to reproduce this issue.
I created a scene with a single button.
I added a test script to change the color of the button as in:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/08f3a6bb-32f8-4f99-aa12-887f4133281b)
I modified the button to have a single GraphicTint effect as in:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/5c2207d1-07cd-4c2b-b94c-cee52c172e5e)
When running the scene in Editor the backplate color that was modified via the TestScript returns to its modified color when the effect finishes as in:

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/1f75aff1-f54b-4fbe-ac35-61b15080d6ad

My reproduction attempt is available in https://github.com/ms-RistoRK/MixedRealityToolkit-Unity/commits/661-bug-tinteffect-prepareframe-and-processframe-constantly-triggered-and-overwriting-the-color/ in case you would like to try it out.

I'll be resolving this issue as unable to reproduce.  Still, we appreciate your contribution to the project and encourage you to submit your suggestion as a pull request and a panel of experts will review it and provide feedback on it.

**Closed by ms-RistoRK** 2024-03-19 20:22 UTC
Labels: Type: Bug, Package: UX Core, Priority: Low

**Comment by Maesla** [comment] 2024-04-01 10:49
I have been checking your example and indeed it works, but because you are changing the color in Start before the color caching take place. 

Use this modification and see how you can reproduce the issue

```csharp
using UnityEngine;
using System.Collections;
using MixedReality.Toolkit.UX;
using UnityEngine.UI;


namespace TMPro.Examples
{
    
    public class SimpleScript : MonoBehaviour
    {

        private TextMeshPro m_textMeshPro;
        //private TMP_FontAsset m_FontAsset;

        private const string label = "The <#0050FF>count is: </color>{0:2}";
        private float m_frame;

        [SerializeField]
        private GameObject testButton;

        IEnumerator Start()
        {
            m_textMeshPro = gameObject.AddComponent<TextMeshPro>();

            yield return new WaitForSeconds(0.1f);
            // Add new TextMesh Pro Component

            m_textMeshPro.autoSizeTextContainer = true;

            // Set various font settings.
            m_textMeshPro.fontSize = 48;

            m_textMeshPro.alignment = TextAlignmentOptions.Center;
            
            m_textMeshPro.enableWordWrapping = false;

            ChangeColor();
        }


        void Update()
        {
            m_textMeshPro.SetText(label, m_frame % 1000);
            m_frame += 1 * Time.deltaTime;

            if (Input.GetKeyDown(KeyCode.Space))
            {
                ChangeColor();
            }
        }


        private void ChangeColor()
        {
            var testButtonVisualizer = testButton.GetComponent<StateVisualizer>();
            var childrenRawImages = testButtonVisualizer.GetComponentsInChildren<RawImage>();
            var backPlateRawImage = childrenRawImages[0];
            backPlateRawImage.color = new Color32(0, 255, 0, 255);
        }
    }
}
```

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/25863696/6d752c76-f4eb-4eb4-a5fb-7681ca1175c2

**Comment by Maesla** [comment] 2024-04-01 10:55
Also, using your exact sample, if you add a log in TintEffect.ProcessFrame, you can see how this method is executed constantly

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/25863696/34b19b2e-9a38-4515-adf2-6b555fb1a908)

https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/25863696/cb1303e2-ed64-44cd-a2b6-8a12acacacf0

**Comment by Maesla** [comment] 2024-04-18 09:58
@AMollis @ms-RistoRK I was able to reproduce the bug with your example, you just have to not do the logic in the start and you can reproduce the bug.

Can we reopen the bug?
