### ISSUE TITLE
[Release] Release MRTK3 packages at commit f279218d1e1f0856ebb32c6122b0b22a273a15d6

### ISSUE THREAD

**Issue by shaynie** [MixedRealityToolkit/MixedRealityToolkit-Unity#697] opened 2024-03-18 20:36 UTC
- [ ] Check Package Versions
- [ ] Create Release Branch
- [ ] Create Release Canidate Packages
- [ ] Create Draft Release on GitHub
- [ ] Microsoft Validates Release Canidate Packages and Release Notes
- [ ] Qualcomm Validates Release Canidate Packages and Release Notes
- [ ] Magic Leap Validates Release Canidate Packages and Release Notes
- [ ] Repackage and Publish to NPM Feed
- [ ] Publish Release on GitHub
- [ ] Update API Reference Documentation

**Comment by AMollis** [comment] 2024-03-19 17:49
Duplicate of 

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/644

**Closed by AMollis** 2024-03-19 17:49 UTC
Labels: Status: Duplicate, Type: Release Management
