### ISSUE TITLE
[BUG] Following MRTK Documentation for Cloned Examples Results in Unity Crash

### ISSUE THREAD

**Issue by xrezdev08** [MixedRealityToolkit/MixedRealityToolkit-Unity#618] opened 2024-01-18 21:37 UTC
## Describe the bug

I'm following the MRTK3 documentation hub pre-requisites checklists and cloning the main branch (or most recent release branch) of MRTK3 from this repository. I open the project in Unity Hub and attempt to run the scenes provided, but Unity crashes on start.

The template projects setup instructions are vague, instead recommending configuring a new project to use the toolkit. However I would like to drop into a demo environment first.

I would like to incorporate MRTK3 into our current project, but until I've interfaced with some examples and know how it works better, I am hesitant to do so. I would like to use the example scenes for reference which means being able to run the example project.

## To reproduce

1. Follow this checklist: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/install-the-tools?tabs=unity
2. Install the correct version of Unity editor with the support modules for UWP https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-dev-env
3. Check this page, which recommends cloning from a branch which no longer exists: https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-template
4. Instead clone from the main branch of this repo.
5. Open project in Unity
6. Switch to UWP Build Target
7. Open the Empty Demo Scene
8. Run, Unity Crashes

## Expected behavior

1. Follow this checklist: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/install-the-tools?tabs=unity
2. Install the correct version of Unity editor with the support modules for UWP https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-dev-env
3. Clone the main or a release tagged MRTK3 source
4. Open the demo project
5. Set build target to UWP
6. Run a demo scene
7. the demo scene opens with either the MRTK Input Simulator or Holographic Remoting (Hololens2)

## Your setup (please complete the following information)

- Unity Version 2021.3.21f1
- MRTK Version 3.0.1 and main commit [694fa6c](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/694fa6c9d2ca56da0978faffa17b07de29d7689e)

## Target platform (please complete the following information)

- HoloLens 2

**Comment by ms-RistoRK** [comment] 2024-01-22 21:09
Hello @xrezdev08 thank you for reaching out.
I tried to reproduce this issue but didn't experience the crash you mentioned.  What I did was a fresh install of Unity Editor 2021.3.21f1 > Cloned MRTK3 main branch > Open the project located in <RepoRoot>\MixedRealityToolkit-Unity\UnityProjects\MRTKDevTemplate and then opened the scene located in  <RepoRoot>\MixedRealityToolkit-Unity\UnityProjects\MRTKDevTemplate\Assets\Scenes\EmptyScene ... I also opened the CanvasExample and HandInteractionExamples scenes but didn't experience a crash either.
I would suggest you to:
* Check if the OS has any updates queued and install them.
* Check if your GPU has driver updates and install them.
* Do a fresh install of your Unity Editor by uninstalling it via Unity Hub, remove it, and wipe out its folder content.
Please let us know if any of the above helped you.

Also, thank you for letting us know of our outdated documentation, we are in the process of updating it.

**Comment by xrezdev08** [comment] 2024-01-23 17:18
Thank you for getting back to me. I will try your suggestions and let you know if any of them help.

**Comment by xrezdev08** [comment] 2024-01-23 18:26
> - Check if the OS has any updates queued and install them.
> - Check if your GPU has driver updates and install them.
> - Do a fresh install of your Unity Editor by uninstalling it via Unity Hub, remove it, and wipe out its folder content.

I have tried the above recommendations with no changes.
**Unity Editor Version:** 2021.2.21f1, freshly installed as suggested
**OS:** WIndows 10 Version	10.0.19045 Build 19045, No Pending Updates
**Graphics:**  RTX 3090Ti, Nvidia Driver Version 546.65, No Available Updates

I am still experiencing a Unity Editor crash when attempting to run SampleEmptyMRTKScene. I have tried after the above steps, both with and without installing the UWP build support as detailed in the "Setting up A Development Environment" section of the documentation. I have also tried and with and without switching to UWP as the target platform before running the demo scene.

Is there another dependency that might be missing or in conflict.

**Comment by ms-RistoRK** [comment] 2024-01-23 18:34
Thank you for your update.  The issue could be related to some missing dependencies.  May I suggest you try setting up MRTK3 packages with Mixed Reality Feature Tool as described [here](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-project)?

**Comment by xrezdev08** [comment] 2024-01-23 18:48
Following this suggestion, it appears the following packages were not labeled as "installed" by the Mixed Reality Feature tool on opening the demo project.

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/137559847/3ce07cbe-be48-4660-97c7-3b82f53485cb)

After installing these packages, attempting to open the project results in the following compilation error in Assets\SampleSceneHandMenu.cs.

> Assets\Scripts\SampleSceneHandMenu.cs(57,39): error CS0103: The name 'FindObjectUtility' does not exist in the current context

**Comment by xrezdev08** [comment] 2024-01-23 18:56
The offending code:
`
SimpleProfiler profiler = FindObjectUtility.FindFirstObjectByType<SimpleProfiler>(true);
`
I was able to get the error to go away by changing it to:
`
SimpleProfiler profiler = FindFirstObjectByType<SimpleProfiler>(FindObjectsInactive.Include);
`
However I am unsure this accomplishes the same goal. I can't seem to find any documentation for the FindObjectUtility mentioned in the original script.

**Comment by xrezdev08** [comment] 2024-01-23 19:32
Double checking the installation checklist again. I installed the HoloLens 2 emulator, but it appears the HoloLens 1 emulator was not installed. Would not having the HoloLens 1 emulator installed cause an editor crash? I tried installing the HoloLens 1 emulator, but at the end I get an installation rollback and the error:

> MSI (s) (68!58) [13:22:51:849]: Product: Windows Mixed Reality Templates for Visual Studio -- Error 1608. This product requires Microsoft Visual Studio 2015 or newer. It also requires the Universal Windows Platform tools optional feature of Visual Studio.
>
>Please install Visual Studio with the Universal Windows Platform tools optional feature and try again.

I have attached the installation logs as much of the information there means next to nothing to me. Hoping someone there might have some insight as to how I might fix or whether I need to bother to move forward troubleshooting.
[HoloLens_Emulator___Windows_10.0.17763.134_20240123132012_004_package_WindowsMixedRealityTemplatesforVisualStudio.log](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/files/14028970/HoloLens_Emulator___Windows_10.0.17763.134_20240123132012_004_package_WindowsMixedRealityTemplatesforVisualStudio.log)

This is a bit odd, because I definitely have a valid installation of VS 2022 with the UWP features installed, as it's a pre-requisite of our other project. I was able to install the HoloLens 2 emulator just fine. For posterity I checked anyway, and I do definitely have VS2022 with UWP installed, with everything enabled in the features for UWP support except Copilot.

**Comment by ms-RistoRK** [comment] 2024-01-23 19:39
Thank you for the follow-up and additional information.  I think the issue may be related to the Unity Editor version you are using.  The failing code was introduced in Unity 2021.**_3_**.18 but I noticed you are using 2021.**_2_**.21f1 as per:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/9a8dc4ad-6605-4fe1-92c3-2d6d2b05e569)
Could you please try upgrading your editor to 2021.**_3_**.21f1 and let us know if the compilation error still appears?

**Comment by xrezdev08** [comment] 2024-01-23 19:47
> Thank you for the follow-up and additional information. I think the issue may be related to the Unity Editor version you are using. The failing code was introduced in Unity 2021.**_3_**.18 but I noticed you are using 2021.**_2_**.21f1 as per: ![image](https://private-user-images.githubusercontent.com/84108471/299081889-9a8dc4ad-6605-4fe1-92c3-2d6d2b05e569.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzkwNDIsIm5iZiI6MTcwNjAzODc0MiwicGF0aCI6Ii84NDEwODQ3MS8yOTkwODE4ODktOWE4ZGM0YWQtNjYwNS00ZmUxLTkyYzMtMmQ2ZDJiMDVlNTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE5MzkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOTI2N2RiMGYyMmVkMmFjYjk1ZTQzMDJkZGEzODllN2M4ZjEyMzBiM2FiMDQ5MmJiODQ1OGEwY2FlZTQ3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vLGp1kayPLMgJpFxQ2x8Q-My1t2ktIermdvyLCVNRvQ) Could you please try upgrading your editor to 2021.**_3_**.21f1 and let us know if the compilation error still appears?

Sorry about that, that's actually just a typo. Thank you for pointing it out!

I am on 2021.3.21f1.

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/137559847/f599b91d-2729-4d3a-9d66-06a87fe784a2)

**Comment by ms-RistoRK** [comment] 2024-01-23 22:11
Ok, thx for the clarification.  The next thing I would check would is having "Visual Studio Tools for Unity" installed.  If you run Visual Studio Installer then go to "Individual components" tab and then scroll down until "Games and Graphics" section.  Check that "Visual Studio Tools for Unity" is checked, for example:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/54fb0c3a-bece-41ea-8df6-db0c5cf3739f)
If it is already checked then I would suggest to uncheck, reboot, check it again to force its re-install.

**Comment by AMollis** [comment] 2024-02-12 23:48
@xrezdev08 , unfortunately at this time we can't reproduce the issue.   We can continue investigate, however we need more information.   Can you provide 1 or more of the following?

1. Your exact copy of the sample Unity Project that is reproducing the issue.  We can't repro using the sample project in the MRTK3 repository.
2. A crash dump contain the Unity crash
3. Your Unity Log file from the Unity crash
4. The compile error before changing MRTK3 code.

**Comment by AMollis** [comment] 2024-02-12 23:56
Also @xrezdev08 , MRTK3 will not work with HoloLens 1, so the HoloLens 1 emulator is not needed.

You should be able to build the MRTK samples with no HoloLens emulator installed.

**Comment by xrezdev08** [comment] 2024-02-13 20:57
Noted, Thank you for clarifying. I wasn't entirely certain I needed it.

Been out sick, but when I get back into the lab I will try to set aside some time to reproduce the crash with minimum steps listed in my original ticket and then send something over.

**Comment by fjaen** [comment] 2024-02-22 06:27
Hi, 
I am also experiencing problems when opening the MRTKDevTemplate project.
I have installed all the MRTK packages using the MRFTool (BTW, the org.mixedrealitytoolkit.data package was missing in the MRFTool and I had to install it from local disc using the corresponding json file of the cloned project). 
After installing the packages and opening the  MRTKDevTemplate project I get the following compilation errors
![imagen](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/18660336/7832c3ab-265f-412d-9d1e-1f8b8bf8eea1)
I have a W11 system, Unity 2021.3.21f1 and the following versions of MRTK3 packages:
org.mixedrealitytoolkit.accessibility: 1.0.1-pre.19
org.mixedrealitytoolkit.audio: 3.0.1
org.mixedrealitytoolkit.core: 3.1.1
org.mixedrealitytoolkit.data: 1.0.1-development
org.mixedrealitytoolkit.diagnostics: 3.0.1
org.mixedrealitytoolkit.extendedassets: 3.0.1
org.mixedrealitytoolkit.input: 3.1.0
org.mixedrealitytoolkit.spatialmanipulation: 3.1.0
org.mixedrealitytoolkit.standardassets: 3.0.1
org.mixedrealitytoolkit.tools: 3.0.1
org.mixedrealitytoolkit.uxcomponents: 3.1.1
org.mixedrealitytoolkit.uxcomponents.noncanvas: 3.1.1
org.mixedrealitytoolkit.uxcore: 3.1.1
org.mixedrealitytoolkit.windowsspeech: 3.0.1

Thanks for your help

**Comment by ms-RistoRK** [comment] 2024-03-19 20:27
Attempted a reproduction in Unity 2021.3.21f1 with MRTK3 commit https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/f279218d1e1f0856ebb32c6122b0b22a273a15d6, unable to reproduce, closing this issue.

**Closed by ms-RistoRK** 2024-03-19 20:27 UTC
Labels: Type: Bug
