### ISSUE TITLE
[BUG] Video has black background on HoloLens 2

### ISSUE THREAD

**Issue by camnewnham** [MixedRealityToolkit/MixedRealityToolkit-Unity#566] opened 2023-11-27 22:31 UTC
## Describe the bug

... Continued from https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10906

## To reproduce

Create a new project with MRTK3.
Add the MRTK XR Rig.
Record/stream video on a HoloLens 2

## Expected behavior

Transparent displays have transparent clear colors

## Screenshots

See other thread for more screenshots / details / discussion
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/19278856/c6e1a619-5ccf-42a9-8e47-6ee5d10629eb)

## Your setup (please complete the following information)

- Unity Version 2022.3.13f1
- MRTK Version 3.0
- Mixed Reality OpenXR Plugin 1.9.0
- OpenXR Runtime 112.2309.20006.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by AMollis** [comment] 2023-11-28 19:14
Closing as a duplicate of the following issue.  This will be fixed with the next update to the input package

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/497

**Closed by AMollis** 2023-11-28 19:14 UTC
Labels: Type: Bug, Needs: Triage, Status: Duplicate
