### ISSUE TITLE
[BUG] HoloLens 2 System Keyboard's dictation is not working with textboxes in MRTK3'

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#490] opened 2023-09-26 23:21 UTC
## Describe the bug

The built in dictation, that is part of the HoloLens 2 keyboard, is not working in the MRTK3.  It sort of works, but it doesn't enter the full text into the text box

## To reproduce

1. Go to 'InputFieldExample.unity' sample scene
2. Click on 'TMP_InputField" text box
3. System keyboard should appear.
4. Click the dictation microphone
5. Say "Testing 123"
6. Pause for a couple seconds
7. Say "Testing ABC"
8. The text box shows "Testing 123 Te"

## Expected behavior

The text box should show "Testing 123 Testing ABC"

## Your setup (please complete the following information)

- Unity Version - 2021.3.21f1
- MRTK Version or Commit - v3.0

## Target platform (please complete the following information)

- HoloLens 2

**Comment by ms-RistoRK** [comment] 2024-03-19 16:09
Attempting reprodution on Unity 2021.3.21f1 commit https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/f279218d1e1f0856ebb32c6122b0b22a273a15d6

**Comment by ms-RistoRK** [comment] 2024-03-19 16:51
Unable to reproduce in Unity2021.3.21f1.  Attempted to reproduce three times, with 3, 4, 5 second pauses.  Everything is working as expected.  Closing this issue.

![20240319_094810_HoloLens](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/6886d7a0-0c5d-4d6d-9175-746fd966c4c7)

**Comment by AMollis** [comment] 2024-03-19 17:46
@ms-RistoRK  I've confirmed I could not reproduce given the steps.

I'm not sure what changed :)

Closing as "not planned"

**Closed** 2024-03-19 17:45 UTC
Labels: Type: Bug, Needs: Microsoft Attention, Priority: Medium
