### ISSUE TITLE
Endless stream of error messages in Unity Editor when a GO with a PressableButton is selected

### ISSUE THREAD

**Issue by KevinKennedy** [MixedRealityToolkit/MixedRealityToolkit-Unity#772] opened 2024-06-08 00:26 UTC
Repro:
- git checkout uxcore-v3.2.1
- Open up the MRTKDevTemplate Unity project - Unity 2022.3.20f1
- Open up the HandInteractionExamples scene
- Select a GameObject with a PressableButton component (like BasicPressableButton)

Result:
- In the Unity Console, you get a per-frame stream of "The serializedObject should not be used inside OnSceneGUI or OnPreviewGUI. Use the target property directly instead.".  This overwhelms the Unity Editor and some background tasks become very slow.

Commenting out the "[CanEditMultipleObjects]" in PressableButtonInspector.cs will make the errors go away.  Not the right fix obviously.

Looks like it was introduced in Change #698

**Comment by ms-RistoRK** [comment] 2024-06-12 21:58
Hello @KevinKennedy, thank you for submitting this issue.  I am trying to reproduce it but I am not able to reproduce the issue.
In order to attempt to reproduce it I:
* Made a clean clone of MRTK3 with the latest [commit](https://github.com/ms-RistoRK/MixedRealityToolkit-Unity/tree/MRTK3-Issue772).
* Confirmed that I have UXCore Package 3.2.1 as in:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/6b39cb50-408e-447e-9561-6c710879c68f)
* Updated Unity Editor version to 2022.3.33f1
* Opened HandInteractionExamples 
* (In both Editor and Play modes) Selected BasicPressableButton GameObject  
... but the console does not flood with "The serializedObject should not ..." messages as in:

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/e352ff87-1f68-4daa-b6a5-104866de0042)

Here is my working branch in case you would like to try it: https://github.com/ms-RistoRK/MixedRealityToolkit-Unity/tree/MRTK3-Issue772

I would suggest you to:
* Update your Unity Editor to 2022.3.33f1
* Update your local repo with latest MRTK3 main branch commits

Could you please confirm if any of the above suggestions fixed your issue?

**Comment by ms-RistoRK** [comment] 2024-06-13 18:13
Hello @KevinKennedy I took another look at this issue and now tried to reproduce it with Unity 2022.3.20f1 as per your report.  I'm still unable to reproduce it in either Editor nor Play mode as shown next:

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/9d565d78-d0e6-4e6d-9bfd-47a8374831ac)

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/43a40a63-7273-41c5-bf44-def6d013ae6c)

I'm thinking it may be the last commit you have from main branch.  I'm using the [latest commit](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/7904bcb75f61f47abdcb7050fbcaca3f1fbfde0d) from main branch.  Could you please share which commit do you have? I'll try to reproduce from that commit.

**Comment by KUNGERMOoN** [comment] 2024-06-19 14:25
I managed to reproduce it in my issue #782

**Comment by KalonMailh** [comment] 2024-07-04 19:57
Hello There, 
I am facing the same issue. Do we have any more information about it ? 

- Custom Unity project - Unity 2022.3.34f1
- MRTK UX Core Scripts 3.2.1
- MRTK Last version of each package, proposed by the package Manager
<img width="257" alt="image" src="https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/174744569/017d2661-30bc-4263-88f0-326132b973af">

- Using ActionButton Prefab

**Comment by So4E** [comment] 2024-07-12 08:33
I have the same issue. Here's a way to reproduce the errors: 
- Created a new Unity 3D project (version 2022.3.11f1 LTS)
- Created a new scene in Unity and imported all mrtk 3 components with Microsoft Mixed Reality Feature Tool as described by Microsoft [here](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-project)
![grafik](https://github.com/user-attachments/assets/9dd5f2e2-1de0-4dea-9d98-f80c87f9ed3a)
- deleted camera and put MRTK XR Rig and MRTK InputSimulator into the scene
- added a nearMenuBase prefab to my scene and edited the buttons (took the first actionButton, duplicated it and changed icons and labels)
- errors keep popping up: 
![grafik](https://github.com/user-attachments/assets/536583a4-ff7d-4417-b75f-994860e0aeeb)

**Comment by jasonhbartlett** [comment] 2024-07-19 16:49
I also just discovered this issue. Basically, the same @So4E with the latest MRTK3 packages.
Unity Version: 2022.3.20f1

Started as soon as I dragged my first Action Button prefab into the scene. The errors stop when either selecting a different object in the scene hierarchy or switching to Game View rather than Scene View in the inspector.

They stop when commenting out the "[CanEditMultipleObjects]" in PressableButtonInspector.cs as mentioned above.

**Comment by nilshof01** [comment] 2024-08-20 08:36
For me this helped: Go to PressableButtonInspector.cs and replace the method OnSceneGui() with: 
`C#

        [DrawGizmo(GizmoType.Selected)]
        private void OnSceneGUI()
        {
            if (!VisiblePlanes || button == null)
            {
                return;
            }

            // Directly gather current information from the button instance
            currentInfo = GatherCurrentInfo();
            DrawButtonInfo(currentInfo, EditingEnabled);
        }

`
At least that is what GPT4o suggested me to do and so far I do not have any errors anymore. ;)

**Comment by MartinHelvig** [comment] 2024-09-04 10:52
Problem by editing mrtk 3 directly is that we can't get updates etc. Should be fixed in MRTK3 directly.

**Closed** 2024-10-23 21:54 UTC
Labels: Package: UX Core, Status: In Review, Status: In Progress
