### ISSUE TITLE
[BUG] EyeGaze scene does not show hand ray

### ISSUE THREAD

**Issue by ms-RistoRK** [MixedRealityToolkit/MixedRealityToolkit-Unity#680] opened 2024-03-12 20:33 UTC
## Describe the bug

EyeGaze scene does not show hand ray

## To reproduce

1. Go to EyeGaze scene
2. Point with your hand to the scene description box
3. See error the hand ray should be visible as in other scenes

## Expected behavior

When using the hand to point inside the scene a pointing ray should be rendered

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.21f1]
- MRTK Version 3 or Commit https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/d74d59f828d9eb6a169a29e6693ba32439d9c068

- HoloLens 2

## Additional context

This was detected as part of manual testing for next release signoff.

**Comment by keveleigh** [comment] 2024-03-13 20:54
Going to close this one as "by design". Since the demo scene is intended to highlight eye gaze, we intentionally turned off hand rays.

**Closed by keveleigh** 2024-03-13 20:54 UTC
Labels: Type: Bug, Status: By Design
