### ISSUE TITLE
[BUG] Random Objects using Interactable Components lose interactivity

### ISSUE THREAD

**Issue by TmorrisMVI** [MixedRealityToolkit/MixedRealityToolkit-Unity#633] opened 2024-02-06 16:04 UTC
## Describe the bug

I am currently experimenting with MRTK3 in Unity 2022.3.16f1. I have created a game that will allow you to poke game objects causing them to highlight and then display some information. However, seemingly randomly, certain game objects stopped having this previously working functionality.  What is more confusing is that other game objects that are identical as far as components go will still have this functionality. I also have noticed that removing the components and re-adding them will temporarily fix these objects. However, over time they will lose it again or if I make a build they will lose it as well. It is always the same game objects that break and the same game objects that continue to work. 

## To reproduce
1. Load into my application in Game Mode in the Unity Editor, or launch the application on an Android device after installing a new build.
2. Reach the point where highlight functionality is enabled (open hand menu, press toggle button to play an animation, move to game object, poke)
3. Observe that certain objects will highlight, and others will not. (i.e. propeller fan blades should all highlight, and only 2 & 5 will highlight out of the 6)

## Expected behavior

All game objects will a custom callout component will highlight when a poke interactor interacts with an interactable, triggering its isPokeSelected onEntered Event inside of the MRTKBaseInteractable Select Events section.

## Screenshots

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/159163209/442e66d7-1730-4460-bd36-e1bae498be3e)

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/159163209/edd1b1be-5581-4d89-8da9-d7ebe00dc9e3)

## Your setup (please complete the following information)

- Unity Version 2022.3.16f1
- MRTK V3.0

## Target platform (please complete the following information)

- Magic Leap2

**Comment by AMollis** [comment] 2024-02-07 18:28
@TmorrisMVI can you please provide a simplified reproduction of the problem.   You mentioned "my application" but I can't find a link to this.

**Comment by AMollis** [comment] 2024-02-07 18:29
@whebertML / @ghazen-ml  one of you might be a good starting point for this bug, since it is with Magic Leap 2

**Comment by whebertML** [comment] 2024-02-07 20:27
@AMollis Sure, we can take a look.  @TmorrisMVI, as @AMollis mentions, can you possibly provide simple reproduction steps in general (on any project)?

**Comment by TmorrisMVI** [comment] 2024-02-07 20:43
@whebertML Sure thing. It should be noted that I cannot reliably find a way to reproduce this bug on demand, though I have confirmed it occurs in a fresh Unity scene with the following setup. I did not try a fresh project, to maintain the current project setup and packages.

From a general standpoint, you will need a Unity scene with the standard MRTK setup. In this scene, you will need an object with a collider component and an MRTKBaseInteractable component. 

In the Base Interactable's "Base XRI Settings" section, you'll need to add the object's collider to the Colliders list.
In the MRTK Events section, you'll need to add a new event to the "Is Poke Selected" events list. This can be any script that allows you to confirm that the object is receiving input.

From there, duplicate the object a few times (I did 6 total objects in my reproduction) to have multiple objects to test with. Then, either enter play mode in the editor or build to an Android app and load it onto a related device. At this point, if the bug is present, certain objects will no longer fire off their poke interactor events. It could be all or none of them, or select objects.

In my test, I had just one object not working. Deleting and re-adding the Base Interactable makes the object work again in the Editor's Play Mode, but building to an app causes it to break again.

Currently, as I am writing this, I do not have authorization to share this project, though I am working to change that. Let me know if any more information is needed.

**Comment by whebertML** [comment] 2024-02-28 18:39
@TmorrisMVI
I was unable to reproduce this issue as described following the setup steps above.  I have a branch with a commit that contains my test scene and scripts to attempt reproduction here:  https://github.com/whebertML/MixedRealityToolkit-Unity/tree/issue633  If you'd like, you could pull that commit and see if you can reproduce.

I was, however, able to see a potential issue if the grab interactor was active (with a pinch pose close to interactable), which can cause the poke interactor to be disabled (see below gif) during that time.  So you'd stop getting IsPoseSelected events in this case.  Is this possibly what you are seeing?

![MRTK3_Issue633](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/58860572/8f465499-313c-447f-b560-c06fcf93fcb8)

**Comment by shaynie** [comment] 2024-03-27 17:17
@TmorrisMVI, please re-open this if it is still an issue.  Closing as no-repro for now.

**Closed by shaynie** 2024-03-27 17:17 UTC
Labels: Type: Bug, Needs: Author Attention, Needs: Repro
